### ISSUE TITLE
Words 用法

### ISSUE THREAD

**Issue by SportPlusX** [tennsinn/Typecho-Plugins#1]
问题重新编辑过了，我以为没人管了。

**Comment by tennsinn** [comment]
是说前台的输出显示吗，当前版本的方法是在页面文件里面调用信息显示，推荐创建“自定义页面”。
具体的调用方法参考readme.md，提供模板输出和单独获取数组两种方式，模板文件template/template.php，自定义页面可参考template/word.php。
